//! The [`RULES`] table itself. Split out of the parent `rules.rs`
//! facade so that file stays under the workspace 500-line limit.
//! Entries are sorted alphabetically by `code`; the four bijection
//! invariants in `diagnostic_codes_locked` pin the table against the
//! source-walked registry, `TERMINAL_CODES`, and every LLR `emits`.

use super::constructors::{cli, context, floors, r, req, req_gap, terminal};
use super::{Domain, RuleEntry};
use crate::diagnostic::Severity;

/// Hand-curated manifest of every emittable code. Sorted by `code`.
/// Additions: append, re-sort, claim in the relevant LLR's `emits`,
/// add a test exercising the emit.
pub const RULES: &[RuleEntry] = &[
    r(
        "BOUNDARY_CARGO_METADATA_FAILED",
        Severity::Error,
        Domain::Boundary,
    ),
    r(
        "BOUNDARY_CONFIG_PARSE_FAILED",
        Severity::Error,
        Domain::Boundary,
    ),
    r(
        "BOUNDARY_CONFIG_READ_FAILED",
        Severity::Error,
        Domain::Boundary,
    ),
    r(
        "BOUNDARY_DAL_A_MISSING_AUXILIARY_MCDC",
        Severity::Error,
        Domain::Boundary,
    ),
    r(
        "BOUNDARY_FORBIDDEN_BUILD_RS",
        Severity::Error,
        Domain::Boundary,
    ),
    r(
        "BOUNDARY_FORBIDDEN_PROC_MACRO",
        Severity::Error,
        Domain::Boundary,
    ),
    r(
        "BOUNDARY_OUT_OF_SCOPE_DEPS",
        Severity::Error,
        Domain::Boundary,
    ),
    r(
        "BOUNDARY_PARSE_METADATA_FAILED",
        Severity::Error,
        Domain::Boundary,
    ),
    r(
        "BOUNDARY_UNKNOWN_IN_SCOPE_CRATE",
        Severity::Error,
        Domain::Boundary,
    ),
    r(
        "BOUNDARY_VERIFY_METADATA_MISSING",
        Severity::Error,
        Domain::Boundary,
    ),
    r("BUNDLE_ALREADY_EXISTS", Severity::Error, Domain::Bundle),
    r(
        "BUNDLE_CARGO_METADATA_FAILED",
        Severity::Error,
        Domain::Bundle,
    ),
    r("BUNDLE_CURRENT_DIR_FAILED", Severity::Error, Domain::Bundle),
    r("BUNDLE_DIRTY_GIT_TREE", Severity::Error, Domain::Bundle),
    r("BUNDLE_GIT_FAILED", Severity::Error, Domain::Bundle),
    r("BUNDLE_HASH_FAILED", Severity::Error, Domain::Bundle),
    r("BUNDLE_IO_FAILED", Severity::Error, Domain::Bundle),
    r(
        "BUNDLE_LOCKED_GRAPH_UNAVAILABLE",
        Severity::Error,
        Domain::Bundle,
    ),
    r("BUNDLE_PARSE_ENV_FAILED", Severity::Error, Domain::Bundle),
    r("BUNDLE_RUN_COMMAND_FAILED", Severity::Error, Domain::Bundle),
    r("BUNDLE_SERIALIZE_FAILED", Severity::Error, Domain::Bundle),
    r("BUNDLE_TOCTOU", Severity::Error, Domain::Bundle),
    r("CHECK_TEST_RUNTIME_FAILURE", Severity::Error, Domain::Check),
    cli("CLI_INVALID_ARGUMENT", Severity::Error),
    terminal("CLI_SUBCOMMAND_ERROR", Severity::Error),
    cli("CLI_UNSUPPORTED_FORMAT", Severity::Error),
    r("CMD_LAUNCH_FAILED", Severity::Error, Domain::Cmd),
    r("CMD_NON_UTF8_OUTPUT", Severity::Error, Domain::Cmd),
    r("CMD_NON_ZERO_EXIT", Severity::Error, Domain::Cmd),
    context("CONTEXT_AMBIGUOUS_SELECTOR", Severity::Warning),
    terminal("CONTEXT_ERROR", Severity::Error),
    terminal("CONTEXT_FAIL", Severity::Error),
    context("CONTEXT_NO_REQUIREMENTS_FOR_SELECTOR", Severity::Warning),
    context("CONTEXT_NO_TRACE_CONFIGURED", Severity::Info),
    terminal("CONTEXT_OK", Severity::Info),
    context("CONTEXT_RUNTIME_ERROR", Severity::Error),
    context("CONTEXT_SELECTOR_OUT_OF_SCOPE", Severity::Error),
    r(
        "COVERAGE_BELOW_THRESHOLD",
        Severity::Error,
        Domain::Coverage,
    ),
    r(
        "COVERAGE_LLVMCOV_MISSING",
        Severity::Error,
        Domain::Coverage,
    ),
    r("COVERAGE_OK", Severity::Info, Domain::Coverage),
    r("COVERAGE_PARSE_FAILED", Severity::Error, Domain::Coverage),
    r("DOCTOR_BOUNDARY_MISSING", Severity::Error, Domain::Doctor),
    r("DOCTOR_CHECK_PASSED", Severity::Info, Domain::Doctor),
    r(
        "DOCTOR_CI_INTEGRATION_MISSING",
        Severity::Warning,
        Domain::Doctor,
    ),
    terminal("DOCTOR_FAIL", Severity::Error),
    r(
        "DOCTOR_FLOORS_BOUNDARY_MISMATCH",
        Severity::Warning,
        Domain::Doctor,
    ),
    r("DOCTOR_FLOORS_MISSING", Severity::Error, Domain::Doctor),
    r("DOCTOR_FLOORS_SLACK", Severity::Warning, Domain::Doctor),
    r("DOCTOR_FLOORS_VIOLATED", Severity::Error, Domain::Doctor),
    r("DOCTOR_MERGE_STYLE_RISK", Severity::Warning, Domain::Doctor),
    r(
        "DOCTOR_MERGE_STYLE_UNKNOWN",
        Severity::Warning,
        Domain::Doctor,
    ),
    r("DOCTOR_NEXTEST_MISSING", Severity::Warning, Domain::Doctor),
    terminal("DOCTOR_OK", Severity::Info),
    r(
        "DOCTOR_OVERRIDE_PROTOCOL_UNDOCUMENTED",
        Severity::Warning,
        Domain::Doctor,
    ),
    r(
        "DOCTOR_QUALIFICATION_MISSING",
        Severity::Error,
        Domain::Doctor,
    ),
    r("DOCTOR_TRACE_EMPTY", Severity::Error, Domain::Doctor),
    r("DOCTOR_TRACE_INVALID", Severity::Error, Domain::Doctor),
    r(
        "DOCTOR_TRACE_NOT_ADOPTED",
        Severity::Warning,
        Domain::Doctor,
    ),
    r(
        "DOCTOR_TRACE_NO_EVIDENCE",
        Severity::Warning,
        Domain::Doctor,
    ),
    r(
        "ENV_ENGINE_RELEASE_PROVENANCE",
        Severity::Warning,
        Domain::Env,
    ),
    r("ENV_STRICT_CARGO_REQUIRED", Severity::Error, Domain::Env),
    r("ENV_STRICT_RUSTC_REQUIRED", Severity::Error, Domain::Env),
    floors("FLOORS_BELOW_MIN", Severity::Error),
    floors("FLOORS_DIMENSION_OK", Severity::Info),
    terminal("FLOORS_FAIL", Severity::Error),
    floors("FLOORS_LOWERED_WITHOUT_JUSTIFICATION", Severity::Error),
    terminal("FLOORS_OK", Severity::Info),
    terminal("GENERATE_FAIL", Severity::Error),
    terminal("GENERATE_OK", Severity::Info),
    r("GIT_CMD_FAILED", Severity::Error, Domain::Git),
    r("GIT_NON_UTF8_PATH", Severity::Error, Domain::Git),
    r("GIT_OTHER", Severity::Error, Domain::Git),
    r("GIT_SHALLOW_CLONE", Severity::Error, Domain::Git),
    r("GIT_STRICT_BRANCH_REQUIRED", Severity::Error, Domain::Git),
    r("GIT_STRICT_DIRTY_REQUIRED", Severity::Error, Domain::Git),
    r("GIT_STRICT_STATE_REQUIRED", Severity::Error, Domain::Git),
    r("GIT_SUBCOMMAND_FAILED", Severity::Error, Domain::Git),
    r("HASH_NON_UTF8_PATH", Severity::Error, Domain::Hash),
    r("HASH_NOT_UNDER_BASE", Severity::Error, Domain::Hash),
    r("HASH_OPEN_FAILED", Severity::Error, Domain::Hash),
    r("HASH_READ_FAILED", Severity::Error, Domain::Hash),
    r("HASH_WALK_FAILED", Severity::Error, Domain::Hash),
    r("HASH_WRITE_FAILED", Severity::Error, Domain::Hash),
    r("INIT_ADOPTION_INCOMPLETE", Severity::Info, Domain::Init),
    r("INIT_CERT_DIR_EXISTS", Severity::Error, Domain::Init),
    terminal("INIT_FAIL", Severity::Error),
    terminal("INIT_OK", Severity::Info),
    r("INIT_TEMPLATE_WRITTEN", Severity::Info, Domain::Init),
    terminal("KEYGEN_FAIL", Severity::Error),
    r("KEYGEN_KEY_EXISTS", Severity::Error, Domain::Keygen),
    terminal("KEYGEN_OK", Severity::Info),
    r("MCP_CARGO_NOT_FOUND", Severity::Error, Domain::Mcp),
    r("MCP_MALFORMED_JSONL", Severity::Error, Domain::Mcp),
    r("MCP_NO_OUTPUT", Severity::Error, Domain::Mcp),
    r("MCP_SUBPROCESS_SPAWN_FAILED", Severity::Error, Domain::Mcp),
    r("MCP_SUBPROCESS_TIMEOUT", Severity::Error, Domain::Mcp),
    r("MCP_VERSION_PROBE_FAILED", Severity::Warning, Domain::Mcp),
    r("MCP_VERSION_SKEW", Severity::Warning, Domain::Mcp),
    r("MCP_WORKSPACE_FALLBACK", Severity::Warning, Domain::Mcp),
    r(
        "POLICY_ASSURANCE_SELECTION_MISSING",
        Severity::Error,
        Domain::Policy,
    ),
    r(
        "POLICY_ONLINE_RESOLUTION_FORBIDDEN",
        Severity::Error,
        Domain::Policy,
    ),
    r("POLICY_UNKNOWN_DAL", Severity::Error, Domain::Policy),
    r("POLICY_UNKNOWN_PROFILE", Severity::Error, Domain::Policy),
    req_gap("REQ_GAP"),
    req("REQ_PASS", Severity::Info),
    req("REQ_SKIP", Severity::Warning),
    r("SCHEMA_COMPILE_FAILED", Severity::Error, Domain::Schema),
    r("SCHEMA_INSTANCE_INVALID", Severity::Error, Domain::Schema),
    r("SCHEMA_PARSE_FAILED", Severity::Error, Domain::Schema),
    r("SIGN_INVALID_KEY", Severity::Error, Domain::Sign),
    r("SIGN_INVALID_SIGNATURE_HEX", Severity::Error, Domain::Sign),
    r("SIGN_KEYGEN_ENTROPY", Severity::Error, Domain::Sign),
    r("SIGN_PUBKEY_ANCHOR_MISMATCH", Severity::Error, Domain::Sign),
    r("SIGN_READ_FAILED", Severity::Error, Domain::Sign),
    r("SIGN_WRITE_FAILED", Severity::Error, Domain::Sign),
    terminal("TESTS_OK", Severity::Info),
    r(
        "TESTS_OUTCOME_PARSE_FAILED",
        Severity::Warning,
        Domain::Tests,
    ),
    r("TRACE_BACKFILL_READ_FAILED", Severity::Error, Domain::Trace),
    r(
        "TRACE_BACKFILL_SERIALIZE_FAILED",
        Severity::Error,
        Domain::Trace,
    ),
    r(
        "TRACE_BACKFILL_WRITE_FAILED",
        Severity::Error,
        Domain::Trace,
    ),
    r("TRACE_DANGLING_LINK", Severity::Error, Domain::Trace),
    r(
        "TRACE_DERIVED_MISSING_DISPOSITION",
        Severity::Error,
        Domain::Trace,
    ),
    r(
        "TRACE_DERIVED_MISSING_RATIONALE",
        Severity::Error,
        Domain::Trace,
    ),
    r(
        "TRACE_DERIVED_MISSING_SAFETY_IMPACT",
        Severity::Error,
        Domain::Trace,
    ),
    r("TRACE_DERIVED_UNREVIEWED", Severity::Error, Domain::Trace),
    r("TRACE_DUPLICATE_TRACE_LINK", Severity::Error, Domain::Trace),
    r("TRACE_EVIDENCE_EMPTY", Severity::Error, Domain::Trace),
    r("TRACE_EVIDENCE_NOT_ADOPTED", Severity::Error, Domain::Trace),
    r(
        "TRACE_EVIDENCE_NOT_CONFIGURED",
        Severity::Error,
        Domain::Trace,
    ),
    r(
        "TRACE_HLR_SURFACE_UNCLAIMED",
        Severity::Error,
        Domain::Trace,
    ),
    r("TRACE_HLR_SURFACE_UNKNOWN", Severity::Error, Domain::Trace),
    r("TRACE_INVALID_LINK_UUID", Severity::Error, Domain::Trace),
    r("TRACE_LINK_FAILED", Severity::Error, Domain::Trace),
    r("TRACE_LINK_OTHER", Severity::Error, Domain::Trace),
    r(
        "TRACE_LLR_MISSING_PARENT_LINKS",
        Severity::Error,
        Domain::Trace,
    ),
    r(
        "TRACE_MISSING_HLR_SYS_TRACE",
        Severity::Error,
        Domain::Trace,
    ),
    r(
        "TRACE_MISSING_VERIFICATION_METHODS",
        Severity::Error,
        Domain::Trace,
    ),
    r("TRACE_OWNERSHIP_VIOLATION", Severity::Error, Domain::Trace),
    r("TRACE_PARSE_FAILED", Severity::Error, Domain::Trace),
    r("TRACE_READ_FAILED", Severity::Error, Domain::Trace),
    r("TRACE_REGISTER_FAILED", Severity::Error, Domain::Trace),
    r("TRACE_SELECTOR_UNRESOLVED", Severity::Error, Domain::Trace),
    r("TRACE_WRONG_TARGET_KIND", Severity::Error, Domain::Trace),
    r(
        "VERIFY_BOUNDARY_BUILD_RS_DETECTED",
        Severity::Error,
        Domain::Verify,
    ),
    r(
        "VERIFY_BOUNDARY_PROC_MACRO_DETECTED",
        Severity::Error,
        Domain::Verify,
    ),
    r(
        "VERIFY_BUNDLE_INCOMPLETE",
        Severity::Warning,
        Domain::Verify,
    ),
    r(
        "VERIFY_BUNDLE_INCOMPLETELY_CLAIMED",
        Severity::Error,
        Domain::Verify,
    ),
    r(
        "VERIFY_CONTENT_HASH_MISMATCH",
        Severity::Error,
        Domain::Verify,
    ),
    r(
        "VERIFY_CROSS_FILE_INCONSISTENCY",
        Severity::Error,
        Domain::Verify,
    ),
    r("VERIFY_DAL_MAP_MISMATCH", Severity::Error, Domain::Verify),
    r("VERIFY_DAL_MAP_ORPHAN", Severity::Error, Domain::Verify),
    r(
        "VERIFY_DETERMINISTIC_HASH_MISMATCH",
        Severity::Error,
        Domain::Verify,
    ),
    terminal("VERIFY_ERROR", Severity::Error),
    terminal("VERIFY_FAIL", Severity::Error),
    r("VERIFY_HASH_MISMATCH", Severity::Error, Domain::Verify),
    r("VERIFY_INVALID_FORMAT", Severity::Error, Domain::Verify),
    r(
        "VERIFY_LLR_CHECK_SKIPPED_NO_OUTCOMES",
        Severity::Info,
        Domain::Verify,
    ),
    r(
        "VERIFY_LLR_TEST_SELECTOR_UNRESOLVED",
        Severity::Error,
        Domain::Verify,
    ),
    r(
        "VERIFY_MANIFEST_PROJECTION_DRIFT",
        Severity::Error,
        Domain::Verify,
    ),
    r(
        "VERIFY_MISSING_HASHED_FILE",
        Severity::Error,
        Domain::Verify,
    ),
    terminal("VERIFY_OK", Severity::Info),
    r("VERIFY_ONLINE_RESOLUTION", Severity::Error, Domain::Verify),
    r(
        "VERIFY_OUTPUT_MANIFEST_EMPTY",
        Severity::Error,
        Domain::Verify,
    ),
    r("VERIFY_PRERELEASE_TOOL", Severity::Error, Domain::Verify),
    r(
        "VERIFY_RUNTIME_BUNDLE_NOT_FOUND",
        Severity::Error,
        Domain::Verify,
    ),
    r("VERIFY_RUNTIME_HASH", Severity::Error, Domain::Verify),
    r(
        "VERIFY_RUNTIME_PARSE_INDEX",
        Severity::Error,
        Domain::Verify,
    ),
    r("VERIFY_RUNTIME_READ_FILE", Severity::Error, Domain::Verify),
    r(
        "VERIFY_RUNTIME_READ_VERIFY_KEY",
        Severity::Error,
        Domain::Verify,
    ),
    r("VERIFY_RUNTIME_SIGNING", Severity::Error, Domain::Verify),
    r("VERIFY_RUNTIME_WALK", Severity::Error, Domain::Verify),
    r("VERIFY_SIGNATURE_INVALID", Severity::Error, Domain::Verify),
    r(
        "VERIFY_SOURCE_BASELINE_EMPTY",
        Severity::Error,
        Domain::Verify,
    ),
    r(
        "VERIFY_TEST_IDENTITY_UNKNOWN",
        Severity::Error,
        Domain::Verify,
    ),
    r(
        "VERIFY_TEST_SUMMARY_ABSENT_ON_FAILED_RUN",
        Severity::Error,
        Domain::Verify,
    ),
    r(
        "VERIFY_TEST_SUMMARY_MISMATCH",
        Severity::Error,
        Domain::Verify,
    ),
    r(
        "VERIFY_TOOL_COMMANDS_FAILED_SILENTLY",
        Severity::Error,
        Domain::Verify,
    ),
    r(
        "VERIFY_TRACE_OUTPUT_NOT_HASHED",
        Severity::Error,
        Domain::Verify,
    ),
    r("VERIFY_UNEXPECTED_FILE", Severity::Error, Domain::Verify),
    r("VERIFY_UNSAFE_PATH", Severity::Error, Domain::Verify),
];
