//! Verify-time guard on test-execution identity.
//!
//! A per-test outcome record whose `module_path` still carries the
//! `__unknown_binary__` sentinel lost its binary identity at capture
//! time — the defect that let LLR `test_selector`s dangle even though
//! the tests ran. Rejecting it here is the regression guard: a bundle
//! generated by a tool that reverts to identity-losing capture fails
//! verification instead of silently shipping unresolvable selectors.

use std::fs;
use std::path::Path;

use super::errors::VerifyError;

/// Sentinel a libtest-text parser emits when it cannot attribute a test
/// to its binary. A machine-readable (nextest) capture never produces
/// it; its presence in a bundle means identity was lost.
const UNKNOWN_BINARY: &str = "__unknown_binary__";

/// Push [`VerifyError::TestIdentityUnknown`] for each outcome record
/// whose `module_path` carries the unknown-binary sentinel. A missing
/// or unparseable `test_outcomes.jsonl` is handled upstream, so this
/// check stays silent on those.
pub fn check_test_identity(bundle: &Path, errors: &mut Vec<VerifyError>) {
    let path = bundle.join("tests").join("test_outcomes.jsonl");
    let jsonl = match fs::read_to_string(&path) {
        Ok(s) => s,
        Err(_) => return,
    };
    for line in jsonl.lines().filter(|l| !l.trim().is_empty()) {
        let rec: serde_json::Value = match serde_json::from_str(line) {
            Ok(v) => v,
            Err(_) => continue,
        };
        let module_path = rec
            .get("module_path")
            .and_then(|v| v.as_str())
            .unwrap_or("");
        if module_path.contains(UNKNOWN_BINARY) {
            let name = rec
                .get("name")
                .and_then(|v| v.as_str())
                .unwrap_or("<unknown>");
            errors.push(VerifyError::TestIdentityUnknown {
                test: format!("{module_path}::{name}"),
            });
        }
    }
}

#[cfg(test)]
#[allow(clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;

    fn write_jsonl(dir: &Path, body: &str) {
        let tdir = dir.join("tests");
        fs::create_dir_all(&tdir).expect("mkdir");
        fs::write(tdir.join("test_outcomes.jsonl"), body).expect("write");
    }

    #[test]
    fn unknown_binary_record_is_rejected() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_jsonl(
            dir.path(),
            "{\"name\":\"foo\",\"module_path\":\"__unknown_binary__\",\"passed\":true}\n",
        );
        let mut errors = Vec::new();
        check_test_identity(dir.path(), &mut errors);
        assert!(matches!(
            errors.as_slice(),
            [VerifyError::TestIdentityUnknown { .. }]
        ));
    }

    #[test]
    fn resolved_identity_passes() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_jsonl(
            dir.path(),
            "{\"name\":\"foo\",\"module_path\":\"evidence_core::bundle::tests\",\"passed\":true}\n",
        );
        let mut errors = Vec::new();
        check_test_identity(dir.path(), &mut errors);
        assert!(errors.is_empty());
    }

    #[test]
    fn absent_file_is_silent() {
        let dir = tempfile::tempdir().expect("tempdir");
        let mut errors = Vec::new();
        check_test_identity(dir.path(), &mut errors);
        assert!(errors.is_empty());
    }
}
